# Generated by Django 3.2.2 on 2021-05-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_rooms_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_description',
            field=models.CharField(default='Elegant Suite with its modern furniture and comfortable living room with fitted carpet, has a smart TV, hot drink amenities, bathrobes, slippers and luxury toiletries.', max_length=1000),
        ),
    ]
