# Generated by Django 3.2.2 on 2021-05-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200314_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
